# consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  # consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 开启心跳
        heartbeat:
          enabled: true
        # hostname: 127.0.0.1
        service-name: ${spring.application.name}